# Generated by Django 3.2.5 on 2021-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='extra_state',
            field=models.JSONField(default=None, null=True, verbose_name='Расширенное состояние'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('ON', 'Включено'), ('OFF', 'Выключено'), ('UNDEFINED', 'Не определено')], default='UNDEFINED', max_length=32, verbose_name='Состояние'),
        ),
    ]
