# Generated by Django 3.2.5 on 2021-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210707_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Девайс', 'verbose_name_plural': 'Девайсы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип устройства', 'verbose_name_plural': 'Типы устройств'},
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(upload_to='device_type', verbose_name='Изображение устройства'),
        ),
    ]
