# Generated by Django 3.2.5 on 2021-07-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('device', '0003_auto_20210713_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetotype',
            options={'verbose_name': 'Девайсы по группам', 'verbose_name_plural': 'Девайсы по группам'},
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='devicetotype',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='devicetotype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.type', verbose_name='Тип устройства'),
        ),
    ]
